server:
  port: 80
eureka:
  client:
    # 是否注册到eureka
    register-with-eureka: true
    # 是否从eureka抓取注册信息，单子点无所谓，多节点必须为true，配合ribbon是否
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  # eureka 显示自定义实例名称，显示ip
  instance:
    instance-id: order80
    prefer-ip-address: true
spring:
  application:
    name: cloud-order-service