CREATE TABLE payment (
 id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
 serial VARCHAR(200) DEFAULT '',
 PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

update AMS_ARCH_CACHE_DATA set ACPT_ID = '999' where ACPT_ID = '20200405141325';